---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: merge-queue-test
  namespace: acmiel-tenant
spec:
  displayName: merge-queue-test
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: merge-queue-test
  namespace: acmiel-tenant
  # annotations:
  #   build.appstudio.openshift.io/request: configure-pac-no-mr
  #   build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
spec:
  application: merge-queue-test
  componentName: merge-queue-test
  source:
    git:
      revision: main
      url: https://github.com/chmeliik/merge-queue-test
      dockerfileUrl: Containerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  # annotations:
  #   image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: merge-queue-test
  namespace: acmiel-tenant
  labels:
    appstudio.redhat.com/application: merge-queue-test
    appstudio.redhat.com/component: merge-queue-test
spec:
  image:
    name: acmiel-tenant/merge-queue-test
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: merge-queue-test-enterprise-contract
  namespace: acmiel-tenant
spec:
  params:
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/registry-standard
  application: merge-queue-test
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/konflux-ci/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
