---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: merge-queue-test
  namespace: acmiel-tenant
spec:
  displayName: merge-queue-test
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: merge-queue-test
  namespace: acmiel-tenant
  # annotations:
  #   build.appstudio.openshift.io/request: configure-pac-no-mr
  #   build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
spec:
  application: merge-queue-test
  componentName: merge-queue-test
  source:
    git:
      revision: main
      url: https://github.com/chmeliik/merge-queue-test
      dockerfileUrl: Containerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  # annotations:
  #   image-controller.appstudio.redhat.com/update-component-image: 'true'
  name: merge-queue-test
  namespace: acmiel-tenant
  labels:
    appstudio.redhat.com/application: merge-queue-test
    appstudio.redhat.com/component: merge-queue-test
spec:
  image:
    name: acmiel-tenant/merge-queue-test
    visibility: public
  notifications:
    - config:
        url: https://bombino.api.redhat.com/v1/sbom/quay/push
      event: repo_push
      method: webhook
      title: SBOM-event-to-Bombino
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: merge-queue-test-enterprise-contract
  namespace: acmiel-tenant
spec:
  params:
    - name: POLICY_CONFIGURATION
      value: merge-queue-test-policy
  application: merge-queue-test
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/konflux-ci/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: merge-queue-test-policy
  namespace: acmiel-tenant
spec:
  description: "custom policy"
  publicKey: "k8s://openshift-pipelines/public-key"
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
        # Tasks from https://github.com/konflux-ci/tekton-tools/tree/main/tasks
        - oci::quay.io/konflux-ci/konflux-vanguard/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:konflux
      config:
        include:
          - "@redhat"
        exclude:
          - test.required_tests_passed:sast-snyk-check
          - test.no_skipped_tests:sast-snyk-check
          - test.required_tests_passed:sast-snyk-check-oci-ta
          - test.no_skipped_tests:sast-snyk-check-oci-ta
          - hermetic_build_task
          - hermetic_task
          - labels.required_labels
          - labels.disallowed_inherited_labels
          - tasks.required_tasks_found:source-build
          - source_image.exists
          - schedule.weekday_restriction
